name: Rolling Build Main
on:
  workflow_dispatch:
  workflow_call:

jobs:
  rolling_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: main
      upstream_workspace: ''
      ref_for_scheduled_build: main
