name: Kilted Build Main
on:
  workflow_dispatch:
  workflow_call:

jobs:
  kilted_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: kilted
      ros_repo: main
      upstream_workspace: ''
      ref_for_scheduled_build: main
