name: PR and Push Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  build-jazzy:
    uses: ./.github/workflows/build-jazzy.yml

  # Only run kilted and rolling, if build jazzy succeeds
  # kilted and rolling will most likely fail anyways if jazzy fails, so we save resources by not running them
  build-kilted:
    needs: build-jazzy
    uses: ./.github/workflows/build-kilted.yml

  build-rolling:
    needs: build-jazzy
    uses: ./.github/workflows/build-rolling.yml
